name: hotfoot
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^0.4.0+8
  # Google Sign In
  google_sign_in: ^4.0.0
  # Firebase Authentication
  firebase_auth: ^0.15.0+1
  # Cloud Firestore
  cloud_firestore: ^0.13.4+2
  # Flutter bloc
  flutter_bloc: ^3.2.0
  # For object comparison by value
  equatable: ^1.0.0
  # For dart annotations
  meta: ^1.1.6
  # For functional programming Either<> type
  dartz: ^0.8.9
  # Service Locator for Dependency Injection
  get_it: ^4.0.0
  # Local Database
  sembast: ^2.3.0
  # For getting platform dependent paths
  path_provider: ^1.6.5
  # To check for internet connection
  data_connection_checker: ^0.3.4
  # For downloading images to Files.
  flutter_cache_manager: ^1.1.3
  # For getting photo images.
  firebase_storage: ^3.1.3
  # For chat
  firebase_database:
  firebase_analytics:
  image_picker:
  # To use font awesome icons
  # instead of using Icon() use FaIcon()
  # Find available icons here => https://fontawesome.com/icons?d=gallery&q
  font_awesome_flutter: ^8.4.0
  # To get device's current location
  geolocator: ^5.3.1
  # For geocoding and reverse geocoding
  geocoder: ^0.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dash_chat: ^1.0.16
  # For GoogleMap Widget
  google_maps_flutter: ^0.5.25
  # For DateFormat functions
  intl: ^0.16.1
  # For firestore geo point
  geoflutterfire: ^2.1.0
  # For tracking the device's location
  location: ^3.0.2
  # For generating QR images
  qr_flutter: ^3.2.0
  # For scanning QR codes
  flutter_barcode_scanner: ^0.1.7

  # TODO: Maybe delete unused ones
  flutter_google_places: ^0.2.3
  google_maps_webservice: ^0.0.16

  rxdart: ^0.23.0
  flutter_speed_dial: ^1.2.4

dev_dependencies:
  # Flutter Unit Tests
  flutter_test:
    sdk: flutter
  # For mocking dependencies in tests
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/asteroid.png
    - assets/flutter_logo.png
    - assets/place-photo-placeholder.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
